### ISSUE TITLE
Make 2018 Mortgage Rate Survey Data available for download from rate spread calc

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#101]
Along with APOR tables, will also need to publish a table of the _Mortgage Rate Survey Data Used to Calculate Rate Spread for Loans Reportable Under HMDA_ (see example link below). I will work w/ Research to produce the table. Similar to APOR tables, it will be updated once per week. 
https://www.ffiec.gov/ratespread/mortgagerates.htm

@jmarin Can we follow the same format and have this data uploaded to S3 by research? We could then make available as a download, the same way we do with the APOR tables. There is no need for the platform to ingest this data, just make the download available directly from S3. 

@wpears @awolfe76 no action to take on this yet, I need to work w/ Research to get the table.

**Comment by keileyo** [comment]
@awolfe76 @wpears Research is going to produce a table with this data for us and upload it to S3. We have two options from there:

1. Make the table available as a direct csv download from S3 
Pros: Think this is the easiest/most straightforward implementation, and also FIs/vendors/stakeholders can have easy access to the data offline
Cons: We need to publish a couple sentences on the sources of the data [Freddie Mac PMMS, and CFPB market research] which would need to be incorporated into the rate spread calculator UI content if we offer the csv table download from there. Of less concern, people may expect the data served in a table on a webpage as that is how the data is displayed now. 

2. Follow a similar approach to the current availability, and make available as a table in a separate github page 
Pros: More consistent with the current availability of the data, and would not need to incorporate extra content about the data sources into the rate spread calculator UI. 
Cons: I think we would still want to offer a download of the data, but serving it to a separate website and offering the DL is less straightforward than just a link to S3.

**Comment by awolfe76** [comment]
I vote for the first one. Adding a bit of content isn't a problem.

Can you give us the link to the way it is now, the table on the page? Just curious.

**Comment by keileyo** [comment]
thanks, yes its in the first comment in the ticket.

**Comment by awolfe76** [comment]
Thanks. Yep, definitely voting the first option. 😄

**Comment by keileyo** [comment]
Mortgage survey data is uploaded to S3 as _SurveyTable.csv_

New content:

Between the second and third paragraph on the rate spread calc UI:

"Mortgage rate survey data used to calculate rate spreads for loans reportable under HMDA is available for download. The data source for the 1 year ARM product is CFPB market research. The data source for all other products in mortgage rate survey data is the Freddie Mac Primary Mortgage Market Survey®"
