### ISSUE TITLE
Add APOR calculation methodology to the rate spread calculator 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#116]
Will need to add the APOR methodology statement to a separate page, like the data requirements (it is long and dense text) and link from the rate spread calculator. I will store the doc in drive and share the link separately. 

Suggest for now just adding a sentence to the end of 2nd paragraph until a whole rate spread re-design can be done. 

"The methodology for determining Average Prime Offer Rates is provided."  Link the word methodology.

**Comment by awolfe76** [comment]
@keileyo - Is this still needed?

**Comment by keileyo** [comment]
yeah, we should still do this.
