### ISSUE TITLE
Remove 12/25-12/31 error message

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#119]
Remove the error message on 12/25-12/31 for the rate spread calc now that 1.21 is in.
@wpears

**Comment by wpears** [comment]
Deployed

**Comment by schbetsy** [comment]
I've updated the values for the affected dates in Production. Once we get the okay from @keileyo, we'll need to remove the error messages again.

**Comment by keileyo** [comment]
The error message can be removed!

**Comment by wpears** [comment]
Deployed ^^;
