### ISSUE TITLE
Message Difference in Parsing Error Line Numbers in LARFT

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform-tools#132]
In HMDA Help we have seen issues where people have created files using the LARFT and then got parsing errors. When they went to review their file they did so in the LARFT Excel sheet and not in the `.txt` file that it had generated, because of this, these users became confused by the line numbers that were returned with the parsing errors. This is because they were using them as row numbers in the Excel sheet. However, the row numbers of the LARFT and the line numbers do not match. The TS is found on the 3rd line of the LARFT and the first LAR is found on the 5th line of the LARFT. As such, these users were unable to identify where the problematic data fields were.

As such, it would be good to communicate to them in some way that there is a discrepancy between the line numbers that are displayed and the row numbers that they should be looking to fix. Maybe this is a message at the top or the ability to select that they are using the LARFT which would change what numbers are displayed (adding 2 to the TS and 3 to the LARs).

**Comment by awolfe76** [comment]
Closing.

We won't add this to the UI. Instead, we have a script to respond to these HMDA Help questions and can create a knowledge article in the future if necessary.
