### ISSUE TITLE
Update (FFVT) for 2019

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-tools#208]
Update File Format Verification Tool (FFVT) for 2019. There are API changes in the backend where `/ts/validate` no longer works. We need to pass in the year so the new API will be `/ts/validate/2018` or `/ts/validate/2019`

**Comment by meissadia** [comment]
@omnipresent07 

I do not see any references to the `/ts/validate` endpoint in the hmda-platform-tools (or hmda-frontend) repo. 

When is this API expected to be used?

**Comment by wpears** [comment]
Yeah, FFVT doesn't use this endpoint, the `/ts/` and `/lar/` endpoints were exclusively used by API filers, IIRC.
