### ISSUE TITLE
Check Digit state simplification

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-tools#43]
`App.jsx` is being used as a bit of a catchall for state, with the side-effects being the whole app is re-rendered on every single user action. State should instead live closer to components so prevent so much render work. We need to think harder here about which component should be responsible for which bit of state and adjust each component's state/event handlers as needed.

**Comment by awolfe76** [comment]
I started to handle some of this using `shouldComponentUpdate`, [here](https://github.com/cfpb/hmda-platform-tools/blob/969664031d1151b6cb49442e7fe6acd9757d1f29/check-digit/src/js/Answer.jsx#L6) for example.

But, from [the react docs](https://reactjs.org/docs/react-component.html#shouldcomponentupdate) 

> Note that in the future React may treat shouldComponentUpdate() as a hint rather than a strict directive, and returning false may still result in a re-rendering of the component.

So, we should probably do this a little cleaner ... like you suggest.
