### ISSUE TITLE
Disable the submission button until input is valid

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-tools#46]
Currently, the user is given no formatting information and doesn't see a problem until they submit the form. When the error shows, two separate (but nearly identical) errors show up which causes some jumping in the page due to reflows. As a user, this feels confusing, jarring, and unfair, as I'm getting what seems to be 2 errors without knowing how to prevent them.

These problems could all be solved with a component that lists the formatting requirements initially and turns red/bolds the failed rules/shows a red X by the failed rules. Could even take inspiration from [hmda-platform-auth](https://github.com/cfpb/hmda-platform-auth/blob/master/keycloak/themes/hmda/login/resources/js/passwordRules.js) to flag potential problems before submission.

**Comment by awolfe76** [comment]
@designlanguage @keileyo - we can use this issue as the "disable the button until valid" issue.

Disabling the submit button until we have valid input will help with the confusion here. There are errors that display above the input `onBlur`, so leaving the input will let them know that any errors exist.
