### ISSUE TITLE
Add/update content

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-tools#47]
Content still needed:

- [x] heading
- [x] short intro

Content that _may_ need updated:

- [x] radio button labels
- [x] input label (for both get and validate)
- [x] submission button text (for both get and validate)

**Comment by colleenms** [comment]
Can we change "get a check digit" to "generate a check digit" throughout? I think this is a better descriptor and would offer the added benefit of matching the language in the reg.

**Comment by keileyo** [comment]
agree with @colleenms - should be "generate" a check digit. I would recommend referring to the loan ID as Loan/Application ID. 

**Header:**
Check Digit Tool 

**Intro:**
The check digit tool performs two primary functions, generating a check digit and validating a ULI. The tool will generate a two digit check digit value based on the combination of LEI and Loan/Application ID provided. The check digit value is then added to the LEI and Loan/Application ID to form the loan or application's ULI.   The tool will also validate a ULI by verifying that the check digit value is calculated in accordance with procedures defined in the regulation Appendix C to Part 1003.

**Comment by keileyo** [comment]
**radio button labels**
- Generate a check digit
- Validate a ULI

**input label**
Above the entry box for generate a check digit, replace "enter a loan ID...." with "Enter the LEI and Loan/Application ID."
![image](https://user-images.githubusercontent.com/13036571/33570280-4fd92748-d8fa-11e7-8f9f-e4c3310bd967.png)

**Comment by designlanguage** [comment]
@keileyo - How about something shorter and a little less detailed for the intro? Maybe something like:

"You can use this tool for two functions. The first is generating a check digit when you enter a loan ID. The second is validating any ULI that you enter by making sure the check digit is calculated correctly."
