### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-tools#48]
Update error messages to better describe the problem.

@keileyo - we can use this issue to make sure we have the correct min/max lengths for the inputs.

**Comment by colleenms** [comment]
I suggest using more positive language in the error messages, similar to our approach for the beta release. For example, "Please enter a loan ID in order to generate a check digit" rather than "You have to enter a loan ID to get the check digit"

**Comment by designlanguage** [comment]
In the platform, the user creates a password from scratch. If they didn't meet the password requirements, they have to go back and create another one, and that can be very frustrating. There's an up-front cost (in user attention) to listing the password requirements, but that cost is worth it to avoid the frustration of having to do it over again.

In the check digit tool, users aren't making up a LEI/Loan ID, they are more likely copying/pasting. So the up-front cost of initially listing the LEI/Loan ID requirements isn't offsetting much of a burden, and I think we should only show errors when they occur.
