### ISSUE TITLE
Add description of ULI and loan id

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-tools#49]
As mentioned in the [initial comment](https://github.com/cfpb/hmda-platform-tools/issues/46#issue-277492983) of #46, add descriptions and/or examples of both the loan id and the ULI. These can be added just below the text input label.

**Comment by keileyo** [comment]
For general guidance:

Universal Loan ID (ULI) is comprised of:
Legal Entity Identifier  which is alphanumeric and 20 characters in length
Loan/Application ID which is alphanumeric and up to 23 characters
Check digit which is numeric and 2 characters 

A ULI can be a minumum of 23 characters and a maximum of 45 characters. The variation comes from the institution's Loan/Application ID which can be between 1 (technically) and 23 characters.

**Comment by keileyo** [comment]
Descriptors:

ULI: The Universal Loan Identifier (ULI) is a unique value assigned to the loan or application. The ULI is comprised of the financial institution's Legal Entity Identifier (LEI), the institution assigned Loan or Application ID, and a two character check digit calculated using the ISO/IEC 7064, MOD 97-10. 

Loan or Application ID:  A value used to identify a loan or application that is comprised of letters, numbers or a combination of both letters and numbers, and is unique within the financial institution.

**Comment by designlanguage** [comment]
I don't see the harm in showing these descriptors below the fields, but I also wonder how much benefit they provide the user.
