### ISSUE TITLE
FFVT - Design Updates

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#6]
1) Align banner at top to the left instead of the right. Alight with the FFVT title. 

![banner alignment](https://cloud.githubusercontent.com/assets/13036571/23377522/511a0a9c-fcfe-11e6-9664-166dda2f7371.png)

2) If possible, update the banner to more closely reflect our banner from pilot. 

![banner](https://cloud.githubusercontent.com/assets/13036571/23377426/05ac62e4-fcfe-11e6-8072-a8cbac90ccd6.png)

**Comment by awolfe76** [comment]
Should we just make it a full banner like on https://beta.consumerfinance.gov/? We had that on the QM tool too.

Plus, then we can update the message later, after its ready, to say something else other than "work in progress".

**Comment by keileyo** [comment]
good idea @awolfe76. @wpears ignore my first alignment suggestion in favor of a full banner (aligned left). 

![full banner](https://cloud.githubusercontent.com/assets/13036571/23381275/db3851ea-fd0b-11e6-894b-f6454841a71d.PNG)
