### ISSUE TITLE
Rate spread calculator content

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#62]
## **edit: see comment at the bottom for cleared language**

Starting a ticket for the rate spread calculator content. Assumption is that the look & feel will be very similar to the check digit tool. 

Heading: 
### Rate Spread Calculator

Text under heading: 

The rate spread calculator generates the spread between the Annual Percentage Rate (APR) and a survey-based estimate of APRs currently offered on prime mortgage loans of a comparable type utilizing the “Average Prime Offer Rates” fixed table or adjustable table, action taken, amortization type, lock-in date, APR, fixed term (loan maturity) or variable term (initial fixed-rate period), and reverse mortgage.

To ensure the most accurate result based on regulatory requirements for reporting rate spread, please use this rate spread calculator for loans with a final action taken on or after January 1st, 2018, and use the old rate spread calculator for loans with a final action taken date prior to January 1st, 2018. Data requirements for the rate spread calculator are provided in accordance with Regulation C effective January 1st, 2018.  

Users will input the following fields: <-- not text in the UI

- Action Taken (Options 1, 2 or 8)
- Reverse Mortgage is 2
- Amortization Type is [Fixed] or [Variable]
- Rate set date (mm/dd/yyyy) _____
- APR% (0.000%) _____
- Loan Term (years) _____

[Calculate Rate Spread] <-- button to calculate rate spread

**Comment by keileyo** [comment]
In the "text under heading" section below, there will be two hyperlinks to separate pages that we also need to create.

1. Average Prime Offer Rates will link to our APOR table publication page 
2. Data requirements will link to a page describing the rate spread calculator inputs. 

Will update this comment with those tickets.

**Comment by awolfe76** [comment]
Should we add a little note somewhere along with the form for the "NA" results?

Something like "If your action type is not 1,2, or 8 OR the reverse mortgage is 1 the rate spread will be NA."

I might have that logic a bit wrong but I think you get the idea.

**Comment by keileyo** [comment]
@awolfe76 the text in the data requirements ( #64) describes just that, but I'm not opposed to including an additional link to the data requirements next to the Action Taken field 

Something like:

Action Taken (we provide 1, 2 or 8 as options to select) and then a small hyperlink next to it like [more info] that takes them to the requirements page explanations.

**Comment by awolfe76** [comment]
Cool. My thought was a quick little thing like that would probably be helpful. They would see it and just know the answer without having to make an API call or go to another page.

**Comment by keileyo** [comment]
maybe a footnote? i'm open to including it on the calculator. 

"If Action Taken Type is 3, 4, 5, 6, or 7 **or** Reverse Mortgage is 1, report Rate Spread as NA."

**Comment by keileyo** [comment]
## **Cleared Language:**

## Rate Spread Calculator

This calculator provides rate spreads for HMDA reportable loans with a final action date on or after January 1st, 2018. Use the prior rate spread calculator for loans with a final action date before January 1st, 2018. 

The rate spread calculator generates the spread between the Annual Percentage Rate (APR) and a survey-based estimate of APRs currently offered on prime mortgage loans of a comparable type utilizing the “Average Prime Offer Rates” fixed table or adjustable table , action taken, amortization type, lock-in date, APR, fixed term (loan maturity) or variable term (initial fixed-rate period), and reverse mortgage.

Data requirements  for the rate spread calculator are provided in accordance with Regulation C effective January 1st, 2018.

-	Action Taken Type (1, 2 or 8) ____
-	Reverse Mortgage is 2 
-	Amortization Type is [Fixed] or [Variable]
-	Rate set date (mm/dd/yyyy) _____
-	APR% (0.000%) _____
-	Loan term (years)_____

Notes on the language:

- "prior rate spread calculator" should link to https://www.ffiec.gov/ratespread/newcalc.aspx
- "data requirements" should link to the content in #63 
- "fixed table" will link to a .csv downloan of the fixed rate APOR table in S3, "adjustable table" will link to a .csv download of the adjustable table in S3
- Do not allow a choice of reverse mortgage = 1. Incorporate the language ""If Action Taken Type is 3, 4, 5, 6, or 7 or Reverse Mortgage is 1, report Rate Spread as NA." on the page so that users understand why they can only choose 1, 2 or 8 for Action Taken Type and why Reverse Mortgage is specified as 2 (Not a reverse mortgage).
