### ISSUE TITLE
Rate spread calculator not returning values

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#77]
Rate spread calculator is returning just a spinning wheel after entering the inputs and clicking the calculate button. 

![image](https://user-images.githubusercontent.com/13036571/34329638-3cd416f8-e8d6-11e7-9368-9c2dff06201f.png)

**Comment by awolfe76** [comment]
Closing, created https://github.com/cfpb/hmda-platform/issues/1416.
