### ISSUE TITLE
Add "back to tool" link of requirements page

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-tools#81]
At, or near, the top of the requirements page we should have a quick link to get back to the tool.

**Comment by designlanguage** [comment]
Or maybe the requirements page opens in a new tab/window instead?

**Comment by awolfe76** [comment]
Something we did on the [rural and underserved tool](https://www.consumerfinance.gov/rural-or-underserved-tool/) was to just put the FAQs below the form itself.

Seems to simplify it even more.

The current link could even just scroll down to that section.

**Comment by designlanguage** [comment]
Is it essential information for a filer to know before they use the tool? If it's more of a disclaimer, I think it can all just live below the tool (like a FAQ) and not be mentioned in the introduction. We should try to avoid mentioning something twice on a page.

**Comment by awolfe76** [comment]
I don't think I would call it "essential". So moving it below seems ok to me.

**Comment by awolfe76** [comment]
Doing this depends on what happens with #116
