### ISSUE TITLE
Update rate spread tool to use new rate spread API interface

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform-tools#90]
Once https://github.com/cfpb/hmda-platform/pull/1419 is released, we need to: 

- [x] Update the [rate spread calculator tool](https://cfpb.github.io/hmda-platform-tools/rate-spread/) to use the new API interface.
- [x] Update the Public API documentation to match [`public-api.md`](https://github.com/schbetsy/hmda-platform/blob/cfb4293be4a1313fcb58d76f6b0611a8a3c0f42d/Documents/public-api.md)

**Comment by wpears** [comment]
Closed by #91
