### ISSUE TITLE
Incorrect rate spread values on 1 year term loans

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#93]
The rate spread calculator is returning "off by 1" results on loans with a term of 1 year. The calculator is actually using the 2 year term APOR for 1 year term loans. 

For example, for the week of 11/6/2017, the APOR on a fixed rate 1 year term loan is 3.15 and the APOR on a fixed rate 2 year term loan is 3.20. If I have an APR of 4.50, i would expect an APOR of 1.35 on the 1 year term and 1.30 on the 2 year term, but im getting 1.30 (with rounding) on the 1 year term. 

![image](https://user-images.githubusercontent.com/13036571/34523156-3df44892-f064-11e7-9892-f477aa3cd371.png)

**Comment by schbetsy** [comment]
Okay to close?

**Comment by wpears** [comment]
Fixed by #91 & backend PR
