### ISSUE TITLE
CSV download of APOR tables

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-tools#95]
We are getting a lot of feedback that people want the APOR tables available as a .csv download, and this was our original requirement on the table downloads. Would like to explore as an enhancement.

**Comment by colleenms** [comment]
To add to the above, one institution shared the following:

As of last year, we were able to link to http://www.ffiec.gov/ratespread/YieldTableFixed.CSV and automatically get that information

**Comment by keileyo** [comment]
talked to @wpears and the easiest implementation of this would be to have research upload both a .csv and a .txt version of the files. Going to check w/ @jmarin when he returns on whether it would cause any complications for the data ingestion to have two of the same file with different extensions in S3

**Comment by keileyo** [comment]
External stakeholders have elevated making the .csv available to a high priority. Implementation means adding the .csv links (and maintaining the .txt files links). 

Open to ideas on implementation. We could just add a sentence to the 2nd paragraph on the rate spread calc:  "APOR tables are offered as CSV files and pipe-delimited text files:
- CSV files: fixed table and adjustable table (hyperlinks)
- Text files: fixed table and adjustable table (hyperlinks)

**Comment by designlanguage** [comment]
@keileyo @awolfe76 @wpears 

 Initially I thought we were just replacing the txt links with csv, but this complicates things a bit and the intro is pretty long already. We might need an immediate solution for this, but if we can step back a bit, I'm wondering if we can we separate this information out a bit.

### Some ideas:

#### Move content out of the intro
* Can the data requirements line go at the bottom of the tool? Doesn't seem necessary to know up front.
* How about making the final action date a question? This makes it harder to skip and it keeps the intro shorter.
* Put the APOR tables in the sidebar. Again, this shortens the intro and calls attention to the tables. This would move the csv upload...

#### Parallel tracks
Uploading a csv has a similar goal as entering a single loan, so we could indicate that visually with a similar treatment and headings.

![screen shot 2018-01-17 at 2 53 03 pm](https://user-images.githubusercontent.com/10562544/35064401-edb83458-fb97-11e7-9ace-ac8c9e091106.png)

**Comment by keileyo** [comment]
@designlanguage I like the new download options! However, it appears that things have done a 180 since yesterday afternoon and we may not need to csvs at all (risk of 2 files seems to now be outweighing the benefits)

A couple of things to note:

1) We need to leave the first paragraph of the intro. Please do not enter before or after January 1st, 2018 as choice. Our calculator almost always **will not** return the correct response if they enter "Before January 1, 2018" and we have an agreement with FRB/FFIEC to use the language already posted and link back to the prior calculator. 

2) Due to the 12/28 APOR date publication issue from a few weeks ago, we are going to need to post a notification on the rate spread calculator eventually (will discuss more offline) but the current suggestion is that goes in as a footnote. So we probably need to re-think where it makes sense to have the data requirements. 

3) There are new requirements regarding what we need to link to from the rate spread calc that need to be incorporated. The first is [101](https://github.com/cfpb/hmda-platform-tools/issues/101) which already has been implemented by a PR and the second is [116](https://github.com/cfpb/hmda-platform-tools/issues/116) which is new as of yesterday.

**Comment by keileyo** [comment]
ok, got confirmation of the direction change. going to just stay with the text files. @designlanguage after our chat this afternoon, lets open a different ticket with redesign ideas.
