### ISSUE TITLE
Add messaging about loan term of 1 year being incorrect

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-tools#96]
Add an alert to the top of the tool to let users know that a loan term of 1 year provides incorrect results.

@keileyo - you can just add the message here.

**Comment by keileyo** [comment]
So I have two ideas on this. 

1) The first is just a banner w/ language:
"The rate spread calculator is providing incorrect results on entries with a loan term of 1 year. We are working on an update to resolve the issue, and we apologize for the inconvenience." 

2) The second idea is skipping a banner and just returning error language when people attempt to enter a loan term of 1 year. "We're sorry, the rate spread on entries with a loan term of 1 year cannot be calculated right now. We are working on an update to resolve the issue."

**Comment by wpears** [comment]
I vote for #2. I can implement this if so.

**Comment by keileyo** [comment]
i am good w/ #2. @awolfe76 thoughts?

**Comment by awolfe76** [comment]
Do it! :)

**Comment by wpears** [comment]
Deployed
